services:
  api:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    container_name: api
    ports:
      - '5000'
    # volumes:
    #   - ./fastapi:/api
    networks:
      kube:
        ipv4_address: 172.20.0.5
    depends_on:
      - mongodb

  mongodb:
    build:
      context: ./mongo
      dockerfile: Dockerfile
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      kube:
        ipv4_address: 172.20.0.6
  
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    networks:
      kube:
        ipv4_address: 172.20.0.7

volumes:
  mongo_data:

networks:
  kube:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16